apiVersion: v1
data:
  actions.cli: "embed-server --std-out=echo --server-config=standalone-openshift.xml\n\necho
    \" ---------- CUSTOM CONFIGURACION ----------\" \necho \" -- Check 'Database info'
    string on logs! --\"\n\n# /subsystem=logging/root-logger=ROOT:write-attribute(name=level,
    value=\"DEBUG\")\n\nbatch\n\nset DB_USERNAME=C##ADMIN\nset DB_PASSWORD=redhat01\nset
    DB_JDBC_URL=jdbc:oracle:thin:@10.131.0.86:1521/ABC\n\nset DB_DRIVER_NAME=oracle\nset
    DB_DRIVER=oracle.jdbc.OracleDriver\nset DB_XA_DRIVER=oracle.jdbc.xa.client.OracleXADataSource\nset
    DB_EAP_MODULE=com.oracle\nset FILE=/opt/eap/extensions/ojdbc8-12.2.0.1.0.jar\nset
    DEPENDENCIES=javax.api,javax.resource.api\nset JNDI_NAME=java:jboss/datasources/KeycloakDS\n\nmodule
    add --name=$DB_EAP_MODULE --resources=$FILE --dependencies=$DEPENDENCIES\n\n/subsystem=datasources/jdbc-driver=oracle:add(driver-name=$DB_DRIVER_NAME,
    driver-module-name=$DB_EAP_MODULE, driver-xa-datasource-class-name=$DB_XA_DRIVER)\n\n/subsystem=datasources/data-source=KeycloakDS:remove()\n\n/subsystem=datasources/data-source=KeycloakDS:add(jndi-name=$JNDI_NAME,
    enabled=true, use-java-context=true, connection-url=$DB_JDBC_URL, driver-name=$DB_DRIVER_NAME,
    user-name=$DB_USERNAME, password=$DB_PASSWORD)\n\necho \"  ---------- CONFIGURATION
    APPLIED! ----------\" \n\nrun-batch\n\nquit"
immutable: false
kind: ConfigMap
metadata:
  labels:
    application: sso
  name: actions-cli-cm
